<!DOCTYPE html>
<html>
    <head>
        <title>Todo App</title>
        <script src="/js/main.js" defer></script>
        <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    </head>
    <body>
        <div class='container'>

        <h1 class="box banner">Todo App</h1>
        <p id="message"></p>
        <div id="todo-container">
        </div>
        <div class="box" class="add-todo">
        
            <form id="addToDo">
                <label>Create a new todo:</label>
                <textarea form="addToDo" id="todo_name" type="text" name="todo_name" rows="1"></textarea>
                <input type="submit" value="Add"/>
            </form>

        </div>
    
        </div>
        
    </body>
</html>
